### ISSUE TITLE
Improve API for SPARQL SELECT query results

### ISSUE THREAD

**Issue by Aklakan** [SANSA-Stack/SANSA-Stack#100]
The .sparql() returning a raw dataframe is a design flaw. We should decide on something more meaningful to return.

This issue combines the related issues SANSA-Stack/SANSA-Query#13 and SANSA-Stack/SANSA-Query#43 into a single one:
SANSA-Stack/SANSA-Query#43 triggers the question of what to return for .sparql() and
SANSA-Stack/SANSA-Query#17 is about if we returned a DataFrame, can we come up with a reasonable and consistent column naming across the sparql engines

**Comment by Aklakan** [comment]
As an update, we are finally moving towards a proper public API for partitioning and SPARQL querying
No more SparqlifyUtils3 anymore then!

Instead, there is now a QueryExecutionSpark which extends Jena's QueryExecution with spark based methods:
```scala
trait QueryExecutionSpark extends org.apache.jena.query.QueryExecution {
  def execSelectSpark(): ResultSetSpark
  def execConstructSpark: RDD[org.apache.jena.graph.Triple]
  def execConstructQuadsSpark: RDD[Quad]
}

trait ResultSetSpark {
  def getResultVars: Seq[Var]
  def getBindings: RDD[Binding]
}
```

The implementation of QueryExecutionSpark delegates the usual Jena methods to the Spark-based ones - giving you the best of both worlds.

An work-in-progress example of the upcoming API looks as follows:
```scala
RDD[Binding] = rddOfTriples // RDD[Tripe]
  .verticalPartition(RdfPartitionerDefault) // Partition data into tables and return a R2rmlMappingCollection
  .sparqlify // Init a sparqlify engine with defaults and the partitioning and return a QueryExecutionFactorySpark
  .createQueryExecution("CONSTRUCT WHERE { ?s ?p ?o }")
  .execConstructSpark() // Create an RDD[Triple]
  .verticalPartition(RdfPartitionerDefault) // Partition again
  .ontop // Init an ontop engine with defaults and the partitioning and return a QueryExecutionFactorySpark
  .createQueryExecution("SELECT * { ?s ?p ?o }")
  .execSelectSpark()
  .getBindings
```

We are currently still working out some details.
For example, we need to ensure that multiple partitions do no cause clashes in the table names (so maybe you want to provide a name somewhere).
Also, instead of .verticalPartition(...) we want to have a single more general partition method that accepts any R2RML-based partitioning strategy.

Another major improvement is the addition of an R2RML layer:
Any partitioning approach that is capable of splitting data into tables together with appropriate R2RML mappings can then be used as input to any engine that can answer SPARQL queries over R2RML views.
Hence, partitioning and query answering is decoupled which in principle allows to use different engines with the same partitioning. In practice this depends on the actual R2ML compliance of the engine and the partitioning approach. For example, a partitioner may yield R2RML with engine-specific features.
At present we implement this for sparqlify and ontop but it provides also a framework for contributions of other engines.

**Comment by Aklakan** [comment]
> In theory, one could create a DataFrame back from the RDD of bindings, but this isn't implemented yet - might also be less efficient for sure. We might add it as an alternative to a follow up release.

Things have progressed since then and for 0.8 we now have a schema mapper that can create a DataFrame from the RDD; although this version does not yet support the inverse mapping of the DataFrame back to the RDD. There will likely be improvements in this regard for 0.9.

Added initial documentation about [how to convert RDD[Binding] to DataFrame](https://github.com/SANSA-Stack/SANSA-Stack/wiki/Mapping-RDD%5BBinding%5D-to-DataFrames) in upcoming SANSA 0.8.

**Comment by tangyong** [comment]
@Aklakan @LorenzBuehmann I want to know the reason of supporting SPARQL-to-SQL rewriter based on Ontop, and What impact will this have on the use of sansa functions?

Thanks!

**Comment by Aklakan** [comment]
Hi @tangyong,

Ontop has a good feature set such as support for aggregation functions, which Sparqlify so far lacks. Also, Sparqlify lacks several definitions for standard SPARQL 1.1 functions. (We plan on providing a comparison table based on conformance test suite results soon).

As a consequence, Ontop enables execution of sophisticated SPARQL queries which was not possible before. So of particular relevance for us now is Ontop's support for analytic queries, but it may also become relevant for #103 (GeoSPARQL).

The architecture of Sansa allows running both engines side by side and possibly adding more engines in the future. (Contributions welcome ;) )
So this change should be a pure improvement without any loss of prior functionality.
One change i could forsee for Sansa 0.9 is to modularize Ontop and Sparqlify such that applications built on Sansa don't have to draw in both dependencies if they only need either.

Some technical notes:

On the API level, there is a `QueryEngineFactory` which has specializations for Sparqlify and Ontop. This class features several methods to configure Ontop or Sparqlify for a given RDD[Triples] or a set of R2RML mappings.
The `QueryEngineFactory` produces `QueryExecutionFactorySpark` objects. `QueryExecutionFactorySpark` produces `QueryExecutionSpark` objects which are subclasses of Jena's conventional `QueryExecution` and thus provide all ofJena's usual query methods (which pull all the data into the driver) together with new methods that keep all the data in RDD[Triple] and RDD[Binding] instances.

 We have introduced a common partitioning infrastructure: Given an RDD[Triple] it can be partitioned into a set of data frames (tables)  together with appropriate R2RML mappings. This information can then be used to configure either Ontop or Sparqlify. While the default partitioner with default configuration generates standard R2RML that should work with either engine, it is also possible to create R2RML that uses non-standard features in order to allow for taking advantage of an engine's features. The `QueryEngineFactory` may use by default a partitioning strategy that yields non-standard R2RML.

**Comment by tangyong** [comment]
Thanks @Aklakan detailed explanation very much! 

I have another question as following:

As is well known, Ontop is a platform to query relational databases as Virtual RDF Knowledge Graphs using SPARQL, so, whether Ontop support quering RDF data from RDF databases or not?

Thanks!

**Comment by Aklakan** [comment]
Afaik Ontop is mostly tied to relational data; i.e. several components require SQL datatype information from the source data.
For Sparqlify this is the same.

That said, we see that certain components actually could be reused for SPARQL querying over RDF views on RDF data; such as expressed using SPARQL CONSTRUCT queries - i.e. querying over the virtual graph expressed by  a construct query. In fact, we have a simple prototype implementation (horribly documented) [in this test case](https://github.com/SmartDataAnalytics/jena-sparql-api/blob/develop/jena-sparql-api-playground/src/test/java/org/aksw/jena_sparql_api/playground/LoticoExamples.java#L175). (There should also be a util method somewhere in the code base that decomposes a construct query into this list of TernaryRelation objects; ternary relation = triple pattern + defining SPARQL graph pattern). The name `VirtualPartitionedQuery` is IMO bad (its a query partitioned by one of its variables), but it not only supports querying over construct queries, but also querying over the virtual graph created by traversing from an initial query's variable via a certain property path: So given a pair of a variable and a graph pattern such as (?s, { ?s a Foobar }) and a traversal via the predicate my:p one can obtain the outgoing virtual graph view 
`CONSTRUCT { ?x ?y ?z } WHERE { ?s a Foobar . ?s my:p ?x .?x ?y ?z }` or the ingoing one: `CONSTRUCT { ?z ?y ?x } WHERE { ?s a Foobar . ?s my:p ?x .?z ?y ?x }` and use this as a basis for rewriting.

This feature presently lacks documentation but overall is working. It is used in our [Facete](https://github.com/hobbit-project/facete3) faceted search framework, where the facet counts (which are derived from a dataset using an analytic SPARQL query) are actually again queryable via the virtual graph exposed using the just described approach.

The main drawback of SPARQL queries over construct queries is that the construct queries themselve provide no information about the values variables can take in order to optimize candidate view selection. I.e. if we e.g. have CONSTRUCT WHERE { ?s ?p ?o } then maybe for a specific dataset the variable ?p can only take the values of IRIs in the rdf namespace - which means that when requesting with a triple pattern whose predicate is known to be bound to something else (e.g. foaf:knows) then we could omit injecting the view into the rewritten query.

So what is needed is a method to attach metadata to such view definitions - which is exactly what #130 is about.
The model extensions will go into the r2rmlx module of the [R2RML API behind Sansa](https://github.com/SmartDataAnalytics/r2rml-api-jena/tree/develop).

Our mid term goal is indeed to reuse modified R2RML mappings to also allow for views over RDF data. In case you are working on something similar maybe its an opportunity for collaboration?

**Comment by Aklakan** [comment]
Closing this issue as the new API is in place since v0.8.0-RC1
For the record a working snippet from one of the test cases:

```scala
      val triplesString =
      """<urn:s1> <urn:p> "2021-02-25T16:30:12Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
        |      """.stripMargin

      import scala.collection.JavaConverters._
      import net.sansa_stack.query.spark._
      import net.sansa_stack.rdf.spark.partition._

      val it = RDFDataMgr.createIteratorTriples(IOUtils.toInputStream(triplesString, "UTF-8"), Lang.NTRIPLES, "http://example.org/").asScala.toSeq
      var graphRdd: RDD[org.apache.jena.graph.Triple] = spark.sparkContext.parallelize(it)

      val qef = graphRdd.verticalPartition(RdfPartitionerDefault).sparqlify /* or ontop */
      val resultSet: ResultSetSpark = qef.createQueryExecution("SELECT ?o { ?s ?p ?o }")
        .execSelectSpark()
      val rdd: RDD[Binding] = resultSet.getBindings
```
