### ISSUE TITLE
Problem on running on CLI

### ISSUE THREAD

**Issue by wiqijan2002** [SANSA-Stack/SANSA-Stack#104]
When i run the examples of SANSA-Stack nothing happen as shown in the snapshot[](url)
![sansa](https://user-images.githubusercontent.com/38495673/85928601-966dc380-b8c7-11ea-9652-8dfdf9dcc551.png)

**Comment by Aklakan** [comment]
Closing as we cannot reproduce the issue with the current development branch. If there is more information feel free to reopen.
