### ISSUE TITLE
I don't know how to use it

### ISSUE THREAD

**Issue by pj001** [SANSA-Stack/SANSA-Stack#123]
I wanted to use the framework to reason my triples, but I couldn't find the relevant reference case documentation. Can I only read the code on GitHub?

**Comment by LorenzBuehmann** [comment]
do you mean 
i) using Scala code and continue with the result in your code or
ii) just take a Jar file and deploy it on the Spark cluster, then compute the inferences and write back to disk?

**Comment by LorenzBuehmann** [comment]
Answer provided in #124
