### ISSUE TITLE
SchemaMapping generation: Handle case of null-only result variable

### ISSUE THREAD

**Issue by Aklakan** [SANSA-Stack/SANSA-Stack#129]
With a SPARQL OPTIONAL block it is possible to create a 'result set column' which is unbound in every binding.
In this case, ResultSetAnalytics.usedDatatypes returns an empty set of datatypes - so the schema mapper will ignore this column.
The schema mapper should be extended to generate columns of a default type if no datatype was found.

**Comment by carstendraschner** [comment]
also remove these print lines

http://dig.isi.edu/age_XMLSchema#integer
http://dig.isi.edu/name_XMLSchema#string_lang
http://dig.isi.edu/hasParent
http://dig.isi.edu/hasSpouse
http://www.w3.org/1999/02/22-rdf-syntax-ns#type
StructType(StructField(seed,StringType,false), StructField(seed__down_age,DecimalType(38,0),false), StructField(seed__down_name,StringType,false), StructField(seed__up_hasParent__down_age,DecimalType(38,0),true), StructField(seed__up_hasSpouse__down_age,DecimalType(38,0),true), StructField(seed__up_hasParent__down_name,StringType,true), StructField(seed__up_hasSpouse__down_name,StringType,true), StructField(seed__down_hasSpouse__down_age,DecimalType(38,0),true), StructField(seed__down_hasParent__down_age,DecimalType(38,0),true), StructField(seed__down_hasSpouse__down_name,StringType,true), StructField(seed__down_hasParent__down_name,StringType,true))

**Comment by Aklakan** [comment]
Null support is now is implemented, waiting for feedback for whether it works as expected for @carstendraschner 's use case

**Comment by Aklakan** [comment]
Closing as this feature seems to be working now.
