### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class net.sansa_stack.rdf.spark.model.rdd.RddOfTriplesOps$

### ISSUE THREAD

**Issue by asmotrich** [SANSA-Stack/SANSA-Stack#134]
I am running a relatively simple code that reads RDF Triples from the NT file, creates the RDD[Triple] and then transforms that RDD into a DataFrame. This works perfectly when running in local mode using Spark 3.0.1 / Scala 2.12.10 / Java 11 and 1.8. However when I try to run this code in Spark standalone mode on the same machine I get the following error:
`java.lang.NoClassDefFoundError: Could not initialize class net.sansa_stack.rdf.spark.model.rdd.RddOfTriplesOps$`. More details in the attached driver log [error.log](https://github.com/SANSA-Stack/SANSA-Stack/files/5986896/error.log).

The important part is that the failing code is initiated as part of the Spark shuffle service, so it is really not being used in the local mode with unit tests. I used the sansa-rdf-spark_2.12:0.7.2-SNAPSHOT module from SANSA-stack snapshot repository. I also experimented with my own compiled version because I've seen similar errors caused by different Scala patch versions. So I made sure everything is compiled with Scala 2.12.10 used by Spark 3.0.1 at runtime. The results with publicly available snapshot and my own code are identical.

Your help will be greatly appreciated.
Regards,
-Azary

**Comment by Aklakan** [comment]
Hm, sometimes we encountered circular init issues with Jena (e.g. using a prefix mapping object triggers jena initializiation which loads a plugin which accesses the prefix mapping which then goes boom).

If you add the statement JenaSystem.init() as a static initializer in your main class or as the first thing in your main method does the problem go away?

**Comment by asmotrich** [comment]
That did not change the behavior at all. Removal of DataFrame IO (to/from Parquet files) did not help either. It looks the issue is purely with this class initialization on every node of the cluster needed for shuffles.

I am writing some tests within sansa-rdf-spark module that use Spark in standalone mode, I'll report here.

**Comment by asmotrich** [comment]
The culprit is the net.sansa_stack.rdf.spark.model.rdd.RddOfTriplesOps implementation itself. In most of the cases code obtains the Spark session instance by calling the SparkSession.builder().getOrCreate() and assigning to a local variable inside a function. But in several cases a class variable is used and shared among those calls. The initialization of a class variable is not possible at the time of class initialization because Spark configuration parameters have not been read yet.

I'd like to submit a pull request for the fix.

**Comment by asmotrich** [comment]
The PR submitted but CI pipeline fails due to unrelated Fink compilation issues.

**Comment by Aklakan** [comment]
Hi thanks for the PR; I have merged it and made a [revision](https://github.com/SANSA-Stack/SANSA-Stack/blob/a36f0b40491bfaece38e7ef90e572dd8b7a360d6/sansa-rdf/sansa-rdf-spark/src/main/scala/net/sansa_stack/rdf/spark/model/rdd/RddOfTriplesOps.scala#L23)  to get the spark session from the rdd itself - it seems to be more future proof that way in case at some point there would be multiple sessions.

**Comment by asmotrich** [comment]
Very nice indeed!

My company is building an engine that is reasoning over the database structure/metadata and tries to guess semantics of the data set. Hopefully we will talk soon about algorithms, something more interesting than Spark sessions:-) I am a big fan of SANSA-stack.

Regards,
-Azary

**Comment by Aklakan** [comment]
Thanks for the warm feedback and looking forward to discussing algorithms :)
