### ISSUE TITLE
Sansa on the use of ontop

### ISSUE THREAD

**Issue by Invincibled** [SANSA-Stack/SANSA-Stack#166]
Hi, Team:

I have noticed that we are using Ontop in Sansa as the RDF transition to SQL mediation, because to use Ontop, we need obda mapping file, I would like to ask, what do you do with the piece, is it dynamically generated? What are they made of?

looking forward to your reply. thank you

**Comment by Aklakan** [comment]
Hi,

The R2RML mapping is generated automatically in [this method](https://github.com/SANSA-Stack/SANSA-Stack/blob/develop/sansa-rdf/sansa-rdf-common/src/main/scala/net/sansa_stack/rdf/common/partition/r2rml/R2rmlUtils.scala#L132) which uses the partitioner output. [The code that sets up the spark tables](https://github.com/SANSA-Stack/SANSA-Stack/blob/develop/sansa-rdf/sansa-rdf-spark/src/main/scala/net/sansa_stack/rdf/spark/partition/core/SparkTableGenerator.scala#L24) is also based on the partitioner output.


The code assembles the R2RML model using our separate [R2RML framework](https://github.com/SmartDataAnalytics/r2rml-api-jena) which provides a flexible and extensible solution for that purpose. A particular highlight is that the R2RML domain classes (e.g. TriplesMap) are just stateless views over a (jena) RDF model. The views themselves are based on annotated interfaces using our [mapper proxy system](https://github.com/SmartDataAnalytics/jena-sparql-api/tree/master/jena-sparql-api-mapper-proxy).

[QueryEngineFactoryOntop](https://github.com/SANSA-Stack/SANSA-Stack/blob/develop/sansa-query/sansa-query-spark/src/main/scala/net/sansa_stack/query/spark/ontop/QueryEngineFactoryOntop.scala) and [QueryEngineFactorySparqlify](https://github.com/SANSA-Stack/SANSA-Stack/blob/develop/sansa-query/sansa-query-spark/src/main/scala/net/sansa_stack/query/spark/sparqlify/QueryEngineFactorySparqlify.scala) use a common interface that takes the jena model with the R2RML mapping as the argument. Ontop features API methods that accept R2RML as a commons-rdf model - and commons-rdf provides a wrapper implementation for jena models.

So while the query engines are decoupled from the partitioner, the R2RML and table *generation* code depends on both the configuration of the [partitioner](https://github.com/SANSA-Stack/SANSA-Stack/blob/develop/sansa-rdf/sansa-rdf-common/src/main/scala/net/sansa_stack/rdf/common/partition/core/RdfPartitioner.scala) and its [generated partitions](https://github.com/SANSA-Stack/SANSA-Stack/blob/develop/sansa-rdf/sansa-rdf-common/src/main/scala/net/sansa_stack/rdf/common/partition/core/RdfPartitionStateDefault.scala#L3). If I am not mistaken, both Sparqlify and Ontop now use the same partitioner (RDFPartitionerDefault). Partitions are specifications for table generation, and standard R2RML does not support mapping language tags from a table column. So the partitioner features an option whether to allow for creation partitions that match triples in multiple languages. Consequently, there is an option whether the generated R2RML should make use of a non-standard rr:languageColumn property.




Cheers

**Comment by Aklakan** [comment]
Closing this issue as it seems to be answered. Feel free to re-open if further questions arise.
