### ISSUE TITLE
Reading-in RDF data

### ISSUE THREAD

**Issue by Prajakta46** [SANSA-Stack/SANSA-Stack#172]
Hello,

I'm attempting to read a "rdf.nt" file in the TripleReader.scala module. However, I am receiving below error.

Error: Missing option --input
Try --help for more information.

I mentioned the file's path where it was requested in the code. Could someone kindly point me in the right direction? Thank you very much.

**Comment by LorenzBuehmann** [comment]
Hi,

can you please show the full command you're running?

In general `Error: Missing option --input` indicates that you simply forgot to provide the argument `--input` as a Java argument - yes, it's hopefully as simple as it sounds.

**Comment by Aklakan** [comment]
Most likely this issue is either solved or irrelevant by now.
