### ISSUE TITLE
Create a jar including all dependencies in a submodule of sansa stack

### ISSUE THREAD

**Issue by huangmatthieu** [SANSA-Stack/SANSA-Stack#173]
Hello all, 
I would like to know if it is possible to create a jar including all the dependencies for example in the submodule sansa-example spark ?
Because i tried by adding these lines in the pom file in this submodule: 

```
 <build>
    <plugins>
      <!-- any other plugins -->
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
      </plugin>
    </plugins>
  </build>
```

Then run this command in this submodule:
mvn clean package 

But no jar with the suffix "jar-with-dependencies" is created in the target file
does anybody have an idea?

**Comment by LorenzBuehmann** [comment]
Hi,

you're basically talking about a so-called Uber-Jar - Maven Shade Plugin is the common way to go.

If you want to build such a Jar based on a given module and all its dependencies, you use two flags

```
-pl, --projects
        Build specified reactor projects instead of all projects
-am, --also-make
        If project list is specified, also build projects required by the list
```

and the profile `dist` to activate the Maven Shade Plugin 


which in your case means you run (from parent directory)

```
mvn -Pdist -pl :sansa-examples-spark_2.12 -am package 
```

**Comment by LorenzBuehmann** [comment]
Answer provided.
