### ISSUE TITLE
Does SANSA-Stack support N-Quads format?

### ISSUE THREAD

**Issue by Rajjat** [SANSA-Stack/SANSA-Stack#183]
Hello,

I am using SANSA-Stack for reading the N-Quads file (spark) :

    val lang = Lang.NQUADS
    val triples = spark.rdf(lang)(input)

But it throws the following exception
"Exception in thread "main" java.lang.IllegalArgumentException: N-Quads syntax not supported yet!"

Does it support the N-Quads format?

**Comment by Aklakan** [comment]
It seems the old spark.rdf(lang)(input) system and the documentation requires an update.

In develop there is already a new `RddRdfSourceFactory` outlined at [here](http://sansa-stack.github.io/SANSA-Stack/rdf/loading-rdf.html#java). (I know its currently a bit empty there, docs should eventually be consolidated at that new site; if we just had some documentation writers...)

The spark.rdf system has to yet be updated to use the RddRdfSourcefactory.

```java
RDD<Triple> rddOfTriples = rdfSource.asTriples();
RDD<Quad> rddOfQuads = rdfSource.asQuads();
RDD<Model> rddOfModels = rdfSource.asModels();
RDD<DatasetOneNg> rddOfDatasets = rdfSource.asDatasets();
// OneNg = Datasets holding exactly 1 Named Graph
```
There is no need to for specifying a language manually as it will be probed for. Of course, you can still force one.

```java
RdfSourceFactory rdfSourceFactory = RdfSourceFactoryImpl.from(sparkSession);
// The source factory will probe for the language if not specified
RdfSource rdfSource = rdfSourceFactory.get("yourFile.nt"); // optionally provide a lang as an extra argument
Lang lang = rdfSource.getLang();
RDD<Quad> rdd = rdfSource.asQuads();
```

Based on the source lang and your requested one, the system will automatically upgrade triples-to-quads or downgrade quads-to-triples.

It's also worth noting that this system should also be able to ingest turtle and trig in parallel (not just ntriples).

**Comment by Rajjat** [comment]
Thanks for the detailed overview. Is it available only for java? Does scala version supports N-Quads format?

**Comment by LorenzBuehmann** [comment]
Hi @Rajjat 
Your code doesn't work for N-Quads because the method signature is fixed to return an RDD of triples. For quads we suggest the following snippet:
``` scala
val quads = spark.nquads(input)
```

**Comment by Rajjat** [comment]
Thanks, @LorenzBuehmann .
