### ISSUE TITLE
Sansa-stack.net website is broken

### ISSUE THREAD

**Issue by wetneb** [SANSA-Stack/SANSA-Stack#219]
All of the URLs I could try on sansa-stack.net give the error "Oops! That page can't be found."

I am not sure how the website is generated, I could not find a repository for it, so I am opening an issue here - I hope that's okay!

**Comment by wetneb** [comment]
Nevermind, http://sansa-stack.github.io/SANSA-Stack/ seems to work! I think it should just be used as the official website :)

**Comment by Aklakan** [comment]
Right, its very confusing if the host URL itself -  http://sansa-stack.github.io - gives a 404. We need to add a landing page there.

**Comment by Aklakan** [comment]
Redirect on http://sansa-stack.github.io/ is now in place. Thanks for the report.
