### ISSUE TITLE
jena 5 upgrade

### ISSUE THREAD

**Issue by Aklakan** [SANSA-Stack/SANSA-Stack#229]
This is a documentation about the issues with upgrade to jena 5.

jena5 is presently no longer compatible with rdf-commons which breaks the ontop integration.

```
*** RUN ABORTED ***
  it.unibz.inf.ontop.com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: 'java.lang.String org.apache.jena.riot.out.NodeFmtLib.str(org.apache.jena.graph.Node)'
  at it.unibz.inf.ontop.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
```

**Comment by Aklakan** [comment]
Running `mvn clean install deploy` ends up in an endless compilation loop in the sansa-sabine module (sansa binding engine).
Might be related to https://github.com/sbt/sbt/issues/6183
In any case, it would be good if the remaining scala part on the sabine module (which essentially contains jena arq's OpExecutor reimplemented on spark) could either be ported to java or moved to a separate module.

**Comment by Friendseeker** [comment]
> Running `mvn clean install deploy` ends up in an endless compilation loop in the sansa-sabine module (sansa binding engine). Might be related to [sbt/sbt#6183](https://github.com/sbt/sbt/issues/6183) In any case, it would be good if the remaining scala part on the sabine module (which essentially contains jena arq's OpExecutor reimplemented on spark) could either be ported to java or moved to a separate module.

I am a scala zinc incremental compiler maintainer. Assuming the project is not using a too out-of-date maven version (that contains known buggy zinc releases), I can look into the issue.

**Comment by Aklakan** [comment]
Hi @Friendseeker

Thanks for your reply; I will check all plugin versions so that they are up to date, and I will also upgrade maven to the latest 3.x.x release and report back whether the issue still persists.

**Comment by Aklakan** [comment]
The issue went away after a bit of restructuring, especially moving the lower-level java/jena code to a separate module. Unfortunately, the sbt issue has not been further analyzed. But for the sake of the sansa project this issue can be closed.

**Comment by Friendseeker** [comment]
> The issue went away after a bit of restructuring, especially moving the lower-level java/jena code to a separate module. Unfortunately, the sbt issue has not been further analyzed. But for the sake of the sansa project this issue can be closed.

Fantastic to hear that! If your team encounter any other serious sbt/zinc issue, just make an issue report anytime and I would like to help!
